import GodotExtensionHeaders

extension GDExtensionVariantType: CustomStringConvertible {
    public var description: String {
        switch self {
        case GDEXTENSION_VARIANT_TYPE_NIL: "Nil"
        case GDEXTENSION_VARIANT_TYPE_BOOL: "Bool"
        case GDEXTENSION_VARIANT_TYPE_INT: "Int"
        case GDEXTENSION_VARIANT_TYPE_FLOAT: "Double"
        case GDEXTENSION_VARIANT_TYPE_STRING: "String"
        case GDEXTENSION_VARIANT_TYPE_VECTOR2: "Vector2"
        case GDEXTENSION_VARIANT_TYPE_VECTOR2I: "Vector2i"
        case GDEXTENSION_VARIANT_TYPE_RECT2: "Rect2"
        case GDEXTENSION_VARIANT_TYPE_RECT2I: "Rect2i"
        case GDEXTENSION_VARIANT_TYPE_VECTOR3: "Vector3"
        case GDEXTENSION_VARIANT_TYPE_VECTOR3I: "Vector3i"
        case GDEXTENSION_VARIANT_TYPE_TRANSFORM2D: "Transform2D"
        case GDEXTENSION_VARIANT_TYPE_VECTOR4: "Vector4"
        case GDEXTENSION_VARIANT_TYPE_VECTOR4I: "Vector4i"
        case GDEXTENSION_VARIANT_TYPE_PLANE: "Plane"
        case GDEXTENSION_VARIANT_TYPE_QUATERNION: "Quaternion"
        case GDEXTENSION_VARIANT_TYPE_AABB: "AABB"
        case GDEXTENSION_VARIANT_TYPE_BASIS: "Basis"
        case GDEXTENSION_VARIANT_TYPE_TRANSFORM3D: "Transform3D"
        case GDEXTENSION_VARIANT_TYPE_PROJECTION: "Projection"
        case GDEXTENSION_VARIANT_TYPE_COLOR: "Color"
        case GDEXTENSION_VARIANT_TYPE_STRING_NAME: "StringName"
        case GDEXTENSION_VARIANT_TYPE_NODE_PATH: "NodePath"
        case GDEXTENSION_VARIANT_TYPE_RID: "RID"
        case GDEXTENSION_VARIANT_TYPE_OBJECT: "Object"
        case GDEXTENSION_VARIANT_TYPE_CALLABLE: "Callable"
        case GDEXTENSION_VARIANT_TYPE_SIGNAL: "Signal"
        case GDEXTENSION_VARIANT_TYPE_DICTIONARY: "Dictionary"
        case GDEXTENSION_VARIANT_TYPE_ARRAY: "Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY: "PackedByteArray"
        case GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY: "PackedInt32Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY: "PackedInt64Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY: "PackedFloat32Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY: "PackedFloat64Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY: "PackedStringArray"
        case GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY: "PackedVector2Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY: "PackedVector3Array"
        case GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY: "PackedColorArray"
        default: fatalError()
        }
    }
}
